### ISSUE TITLE
How I can refresh page on code change?

### ISSUE THREAD

**Issue by Kiho** [samlam/sveltekit-adapter-dotnetcore#1]

**Comment by samlam** [comment]
the sample dotnet/Razor application should detect changes in the build folder. Try re-run the  `npm run build` command in the Razor project, that should update the index.cjs file.

it is possible to use nodemon detect changes in the Scripts folder.


EnableFileWatching is enabled in NodejsExtensions.cs file 
```csharp
	if (Debugger.IsAttached)
	{
		options.EnableFileWatching = true;
```
