### ISSUE TITLE
Not working with current version of svelte-kit

### ISSUE THREAD

**Issue by Kiho** [samlam/sveltekit-adapter-dotnetcore#2]
I tried to make this work with 1.0.0-next.324 but no success.

**Comment by samlam** [comment]
Let me give it a try today, I haven't tested it with the recent version

**Comment by Kiho** [comment]
I finally figure out issues myself https://github.com/Kiho/svelte-adapter-aspcore but I doubt about performance of solution.

**Comment by samlam** [comment]
I've applied a temp fix, there are few problems still need fixing.

**Comment by samlam** [comment]
Issues are resolved, adapter should work with the latest sveltekit
