### ISSUE TITLE
Unable to use with npm 8

### ISSUE THREAD

**Issue by WolfspiritM** [samlam/sveltekit-adapter-dotnetcore#5]
Hi,

I wanted to give this a try but it doesn't work with npm 8.

```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: sveltekit-adapter-dotnetcore@0.1.6
npm ERR! notsup Not compatible with your version of node/npm: sveltekit-adapter-dotnetcore@0.1.6
npm ERR! notsup Required: {"node":">=16","npm":"~7"}
npm ERR! notsup Actual:   {"npm":"8.5.5","node":"v16.15.0"}
```

**Comment by samlam** [comment]
that's a npm error. you should try the steps mentioned in the readme

```
pnpm install

pnpm -r build
```

if you don't have pnpm , install it globally `npm install -g pnpm`.

It seems to work fine with the latest node.js v18+ and npm v8+

**Comment by WolfspiritM** [comment]
> if you don't have pnpm , install it globally `npm install -g pnpm`.
> 
> It seems to work fine with the latest node.js v18+ and npm v8+

I prefer to use npm and I don't really see why this would be a npm issue.

https://github.com/samlam/sveltekit-adapter-dotnetcore/blob/main/package.json#L31

States that only npm 7 is supported. I think this should be changed to also support npm 8.
Or is there a reason why only npm7 is supported?

**Comment by samlam** [comment]
This is a monorepo (due to multiple package.json files). In my personal experience, `pnpm` has better performance when installing and building monorepo. It may be possible to add npm workspaces,  give me a day or so.

**Comment by timgblack** [comment]
Sorted this out in https://github.com/samlam/sveltekit-adapter-dotnetcore/pull/7 😄

**Comment by samlam** [comment]
correct, closing this issue
